---
title: "CHI calculation"
output: html_document
---

This script summarizes all impacts to calculate Cumulative Human Impacts for each year.


## Loading packages

```{r setup, include=FALSE}

library(raster)
library(RColorBrewer)
library(sf)
library(dplyr)
library(stringr)
library(doParallel)
library(foreach)
library(parallel)
library(here)

#source("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2018/gh-pages/src/R/spatial_common.R")

```

## Reading in data files
```{r}

# Years

years <- 2003:2013
years_subset <- paste(years, collapse="|")

```


## Calculation of CHI
This sums the impact rasters to calculate CHI.
```{r}

# select stressors with all years of data to include in model

stressors <- list.files(file.path(here(), "raw_data/Human_footprint/stressor_impacts"))
stress_all <- str_sub(stressors, 1, str_length(stressors)-16)
stress_length <- table(stress_all) # each should be 11 (or however many years)
stressors_all_yrs <- names(stress_length[stress_length == length(years)])

stressors_chi <- list.files(file.path(here(), "raw_data/Human_footprint/stressor_impacts"),
                            full=TRUE)

stressors_chi <- grep(paste(stressors_all_yrs, collapse="|"), stressors_chi, value=TRUE)

length(stressors_chi)/length(years) # needs to be a whole number

#registerDoParallel(4) 
#years <- 2015:2022
#foreach(year = years,.packages="dplyr") %dopar%{ # year=2014
  
for(year in years){

  stressors_yr <- grep(year, stressors_chi, value=TRUE)
  print(length(stressors_yr))
  
  stress_stack <- raster::stack(stressors_yr)
  
  raster::calc(stress_stack, fun=sum, na.rm=TRUE,
               filename=file.path(here(), sprintf("output_data/HFP/tmp/summed_raster_%s.tif", year)), 
               overwrite=TRUE, progress="text")
  
}

```

This checks to make sure that each year has the correct number of impacts.
```{r}
years = 2003:2013
chi_check <- data.frame(year=years, length=c(NA))


for(year in years){
  stressors_yr <- grep(year, stressors_chi, value=TRUE)

  chi_check$length[chi_check$year == year] <- length(stressors_yr)
 
}

## these should all have the same number and it should reflect the number of stressors
chi_check
```


Final formatting of raster, masking the ocean area.
```{r}

ocean<-raster(here("raw_data/ocean.tif"))

for(year in years) {

  summed_rast <- raster::raster(file.path(here(), sprintf("output_data/HFP/tmp/summed_raster_%s.tif", year)))

  raster::mask(summed_rast, ocean,
                  filename=file.path(here(), sprintf("output_data/HFP/cumulative_impact/direct_chi_%s.tif", year)),
                  overwrite=TRUE)
  print(year)
}

```
