---
title: "Clean_CAPAD"
author: "Caitie"
date: "2024-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r}
library(sf)
library(here)
library(tidyverse)
library(lubridate)
```

# Load data

Downloaded from: https://fed.dcceew.gov.au/datasets/782c02c691014efe8ffbd27445fe41d7_0/explore

```{r}
capad<-st_read(here("raw_data/CAPAD/Collaborative_Australian_Protected_Areas_Database_(CAPAD)_2022_-_Marine.shp"))
```

# All

```{r}
capad<- capad %>% 
  st_make_valid(.) %>% #fix errors in geometry
  mutate(Year = year(GAZ_DATE)) %>% #Create Year column
  st_transform(., "EPSG:3577") #Re-project data to an equal area projection
```


```{r}
capad_diss<-capad %>% 
  group_by(Year) %>%  # Dissolve by Year
  summarise(GIS_AREA = sum(GIS_AREA, na.rm = T)) %>% #Sum GIS area
  mutate(area_km2 = as.numeric(st_area(.))*1e-6) #re-calculate area
```


```{r}
st_write(capad_diss, here("output_data/Capad_baseline/All_MPA_baseline.shp"), append = FALSE)
```


#Total amount protected in 2022
```{r}

capad_2022<-capad %>% 
  mutate(diss = 1) %>% 
  group_by(diss) %>% 
  summarise(.)

strict_2022<-capad %>% 
  filter(IUCN %in% c("Ia", "II", "III")) %>%
  mutate(diss = 1) %>% 
  group_by(diss) %>% 
  summarise(.)

non_strict_2022<-capad %>% 
  filter(IUCN %in% c("IV", "V", "VI")) %>% 
  mutate(diss = 1) %>% 
  group_by(diss) %>% 
  summarise(.)

st_write(capad_2022, here("output_data/Capad_baseline/Full_capad_2022.shp"), append = FALSE)
st_write(strict_2022, here("output_data/Capad_baseline/Full_strict_2022.shp"), append = FALSE)
st_write(non_strict_2022, here("output_data/Capad_baseline/Full_non_strict_2022.shp"), append = FALSE)

```


##All by year 

```{r}
years<-min(capad$Year):max(capad$Year)

for(i in 1:length(years)){
  print(years[[i]])

 capad_<- capad %>% 
  group_by(Year) %>%  # Dissolve by Year
  filter(Year <= years[i])%>%
  summarise(GIS_AREA = sum(GIS_AREA, na.rm = T)) %>% #Sum GIS area
  mutate(area_km2 = as.numeric(st_area(.))*1e-6) #re-calculate area 
  
st_write(capad_,here(paste0("output_data/Capad_baseline/capad_baseline_", years[[i]],".shp")), overwrite = FALSE)

strict<- capad %>% 
  filter(IUCN %in% c("Ia", "II", "III")) %>% 
  group_by(Year) %>%  # Dissolve by Year
  filter(Year <= years[i])%>%
  summarise(GIS_AREA = sum(GIS_AREA, na.rm = T)) %>% #Sum GIS area
  mutate(area_km2 = as.numeric(st_area(.))*1e-6) #re-calculate area
  
st_write(strict,here(paste0("output_data/Capad_baseline/Strict_baseline_", years[[i]],".shp")), overwrite = FALSE)

non_strict<- capad %>% 
  filter(IUCN %in% c("IV", "V", "VI")) %>% 
  group_by(Year) %>%  # Dissolve by Year
  filter(Year <= years[i])%>%
  summarise(GIS_AREA = sum(GIS_AREA, na.rm = T)) %>% #Sum GIS area
  mutate(area_km2 = as.numeric(st_area(.))*1e-6) #re-calculate area
  
st_write(non_strict,here(paste0("output_data/Capad_baseline/Non_strict_baseline_", years[[i]],".shp")), overwrite = FALSE)

}

```


```{r}
st_write(capad_diss_2013, here("output_data/All_MPA_baseline_2013.shp"), append = FALSE)
```




# Strict
```{r}
strict<-capad %>% 
  filter(IUCN %in% c("Ia", "II", "III")) %>% 
  group_by(Year) %>%  # Dissolve by Year
  summarise(GIS_AREA = sum(GIS_AREA, na.rm = T)) %>% #Sum GIS area
  mutate(area_km2 = as.numeric(st_area(.))*1e-6) #re-calculate area
  
```


```{r}
st_write(strict, here("output_data/Strict_baseline.shp"), append = FALSE)
```

# Non-strict

```{r}
non_strict<-capad %>% 
  filter(IUCN %in% c("IV","V", "VI")) %>% 
  group_by(Year) %>%  # Dissolve by Year
  summarise(GIS_AREA = sum(GIS_AREA, na.rm = T)) %>% #Sum GIS area
  mutate(area_km2 = as.numeric(st_area(.))*1e-6) #re-calculate area
```


```{r}
st_write(non_strict, here("output_data/Non_strict_baseline.shp"), append = FALSE)
```


