---
title: "Untitled"
author: "Jade"
date: "2024-06-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Link for climetrics package - https://cran.r-project.org/package=climetrics 
```{r}
#install.packages("climetrics")
library(climetrics)
library(terra)
library(raster)

#install.packages("exactextractr")
library(exactextractr)

#install.packages("ncdf4")
library(ncdf4)

library(lubridate)

#This package unavailable for this version of R - find alternate if needed 
#install.packages("gdal_utils")
#library(gdal_utils)

library(sf)
library(here)
library(tidyverse)
```


#Download data 

```{r}
#NEW SST 
#https://www.metoffice.gov.uk/hadobs/hadisst/data/download.html

filename2<- here("raw_data/Climate_velocity/HadISST/HadISST_sst.nc")
data <- nc_open(filename2)
```

```{r}

sst_brick <- brick(filename2)

plot(sst_brick)
```

#extract mean temp. per year
```{r}
years<-c(1916:2022)

for(i in 1:length(years)){
sub_x<-subset(x = names(sst_brick), grepl(years[i], names(sst_brick))) 
sub_sst<-subset(x = sst_brick, sub_x)
sub_sst_mean<-mean(sub_sst, na.rm = T)

writeRaster(sub_sst_mean, here(paste0("raw_data/Climate_velocity/HadISST/SST_",years[[i]],".tif")), overwrite = T)
}

```


#create rast of mean temps
```{r}
sst_files<-list.files(here("raw_data/Climate_velocity/HadISST"), pattern = ".tif", full.names = T)

sst<-stack(sst_files)

start_date <- as.Date("1916-12-31")
end_date<- as.Date("2022-12-31")

time<- seq.Date(start_date, end_date, by = "year")

sst_byyear <- rts(sst, time)
```


#find velocity
```{r}
ve <- gVelocity(sst_byyear)

plot(ve) 

```

```{r}
#trial 

start_date2 <- as.Date("2010-12-31")
end_date2<- as.Date("2019-12-31")

time2<- seq.Date(start_date, end_date, by = "year")

sst_files2<-list.files(here("raw_data/Climate_velocity/HadISST"), pattern = "SST_201", full.names = T)

sst2<-stack(sst_files)
sst_test <- rts(sst2, time2)

testve<- gVelocity(sst_test)

plot(testve)
```


#fit to aus data 
```{r}
ve_rast <- rast(ve)
ve_project<- project(ve_rast, "epsg:3577")

#load in eez 
eez<- st_read(here("output_data/projected_eez.shp"))

ve_clip<- crop(ve_project, eez, mask = TRUE)

plot(ve_clip)
```

#Resample to fit hf resolution 
```{r}
hf<- rast(here("raw_data/Human_footprint/Direct_high_impact_10perc_2003.tif"))

hf_project <- project(hf,"epsg:3577")

ve2<- terra::resample(ve_clip, hf_project, method = "bilinear")

```


```{r}
#load in capad 
strict<- st_read(here("output_data/Capad_baseline/Strict_baseline.shp"))

non_strict<-st_read(here("output_data/Capad_baseline/Non_strict_baseline.shp"))

capad_extract<-exactextractr::exact_extract(ve_clip, strict, "mean", progress = T, append_cols = T)
```

```{r}
view(capad_extract)

plot(capad_extract)
```

