---
title: "Untitled"
author: "Jade"
date: "2024-07-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(sf)
library(here)
library(tidyverse)
library(lubridate)
library(terra)
```

#Load in EEZ data 
```{r}
#eez<- vect(here("raw_data/EEZ/au_eez_pol_april2022.shp"))

#eez_project <- project(eez, "epsg:3577")

#writeVector(eez_project, here("output_data/projected_eez.shp"), overwrite = FALSE)
#save as a reprojected file 

project_eez <- vect(here("output_data/projected_eez.shp"))
#read in projected layer 
```

#Set up for creating adjusted capad data sets 
```{r}
years<- c(2003:2013)

hfp_files<- list.files(here("output_data/HFP/wilderness/direct_wilderness"),"Direct_high_impact",full.names = TRUE)

capad_files<- list.files(here("output_data/Capad_baseline"), "capad_baseline", full.names = TRUE)
capad_files2<- capad_files[grep("shp", capad_files)]

strict_files<- list.files(here("output_data/Capad_baseline"), "Strict_baseline", full.names = TRUE)
strict_files2<- strict_files[grep("shp", strict_files)]

non_strict_files<- list.files(here("output_data/Capad_baseline"), "Non_strict_baseline", full.names = TRUE)
non_strict_files2<- non_strict_files[grep("shp", non_strict_files)]
```

```{r}
old <- rast(here("output_data/HFP/wilderness/direct_wilderness/Direct_high_impact_10perc_2003.tif"))


```

#create adjusted capad data sets 
```{r}
for(i in 1:length(years)){
print(years[[i]])  
  
sub_hfp<- rast(hfp_files[grep(years[[i]],hfp_files)])

#get the human impact data
project_impact<- project(sub_hfp, "epsg:3577")
impact_clip<- crop(project_impact, project_eez, mask = TRUE)
#impact_valid <- classify(impact_clip, cbind(NA, 0))
impact_poly<- as.polygons(impact_clip)

#remove intersect between hfp and capad 
sub_capad<- st_read(capad_files2[grep(years[[i]],capad_files2)])

sub_capad1<- sub_capad%>%
  st_make_valid(.)
sub_capad2<- vect(sub_capad1)

capad_intersect<- intersect(sub_capad2, impact_poly)

capad_adjust<- erase(sub_capad2,capad_intersect)

#plot(sub_capad2)
#plot(impact_clip, col = "yellow", add = TRUE)
#plot(capad_adjust, col = "blue", add = TRUE)

#update the area column
capad_adjust$new_capad_area<- capad_adjust%>% expanse(.)*1e-6


#strict capad
sub_strict<- st_read(strict_files2[grep(years[[i]],strict_files2)])
sub_strict1<- sub_strict%>%
  st_make_valid(.)
sub_strict2<- vect(sub_strict1)

strict_intersect<- intersect(sub_strict2, impact_poly)
strict_adjust<- terra::erase(sub_strict2,strict_intersect)

strict_adjust$new_strict_area<- strict_adjust%>% expanse(.)*1e-6

#non-strict capad
sub_non_strict<- st_read(non_strict_files2[grep(years[[i]],non_strict_files2)])
sub_non_strict1<- sub_non_strict%>%
  st_make_valid(.)
sub_non_strict2<- vect(sub_non_strict1)
non_strict_intersect<- intersect(sub_non_strict2, impact_poly)
non_strict_adjust<- terra::erase(sub_non_strict2,non_strict_intersect)

non_strict_adjust$new_non_strict_area<- non_strict_adjust%>% expanse(.)*1e-6


writeVector(capad_adjust,here(paste0("output_data/Capad_adjusted/capad_adjust_", years[[i]],".shp")), overwrite = TRUE)

writeVector(strict_adjust,here(paste0("output_data/Capad_adjusted/strict_adjust_", years[[i]],".shp")), overwrite = TRUE)

writeVector(non_strict_adjust,here(paste0("output_data/Capad_adjusted/non_strict_adjust_", years[[i]],".shp")), overwrite = TRUE)

}

```


```{r}
plot(st_read(here("output_data/Capad_adjusted/non_strict_adjust_2003.shp")))
```

Total area in last year (currently 2013)
```{r}
capad_2013<- st_read(here("output_data/Capad_adjusted/capad_adjust_2013.shp"))
strict_2013<- st_read(here("output_data/Capad_adjusted/strict_adjust_2013.shp"))

non_strict_2013<- st_read(here("output_data/Capad_adjusted/non_strict_adjust_2013.shp"))

capad<-capad_2013 %>% 
  mutate(diss = 1) %>% 
  group_by(diss) %>% 
  summarise(.)

strict<-strict_2013 %>% 
  mutate(diss = 1) %>% 
  group_by(diss) %>% 
  summarise(.)

non_strict<-non_strict_2013 %>% 
  mutate(diss = 1) %>% 
  group_by(diss) %>% 
  summarise(.)

st_write(capad, here("output_data/Capad_adjusted/Full_capad_2013_corrected.shp"), append = FALSE)
st_write(strict, here("output_data/Capad_adjusted/Full_strict_2013_corrected.shp"), append = FALSE)
st_write(non_strict, here("output_data/Capad_adjusted/Full_non_strict_2013_corrected.shp"), append = FALSE)
```

