---
title: "Untitled"
author: "Caitie"
date: "2024-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(ggplot2)
library(here)
library(tidyverse)
```


#Colours 

```{r}
colPalette <- c("#3B3561", "#ECA72C", "#226F54","#B8D4E3", "#C06E52","#01172F")
``` 


# Plot PE through time

```{r}
pe<-read_csv(here("output_data/results/PE_baseline_calculations.csv"))
```

##Create new data frame for PE
```{r}
pe_long <- pivot_longer(pe, cols= c("CAPAD_PE", "Strict_PE", "Non_strict_PE"),
                         names_to = "PE_type",
                         values_to = "PE")

pe_long<- pe_long%>% 
  dplyr::select(-c(CAPAD_N,Strict_N,Non_strict_N))
```

##Plot
```{r}

ggplot(pe_long, aes(x = Year, y = PE, col = PE_type)) +
  geom_line() +
  theme_bw() +
  scale_colour_discrete(type = colPalette, labels = c("All MPAs", "Non-strict", "Strict")) +
  labs(title = "Ecoregion Protection Equality - Baseline",
      y = "Protection equality",
      x = "Year", 
      col = "Protected area class")
   

```



```{r}
ggsave(here("figures/All_PAs_Protection_equality.png"), width = 10, height= 6)
```

# Plot corrected PE through time 

```{r}
pe_corrected<-read_csv(here("output_data/results/PE_corrected_calculations.csv"))
```

##Create new data frame for PE
```{r}
pe_corrected_long <- pivot_longer(pe_corrected, cols= c("CAPAD_PE", "Strict_PE", "Non_strict_PE"),
                         names_to = "PE_type",
                         values_to = "PE")

pe_corrected_long<- pe_corrected_long%>% 
  dplyr::select(-c(CAPAD_N,Strict_N,Non_strict_N))
```


##Plot
```{r}

ggplot(pe_corrected_long, aes(x = Year, y = PE, col = PE_type)) +
  geom_line() +
  theme_bw() +
  scale_colour_discrete(type = colPalette, labels = c("All MPAs", "Non-strict", "Strict")) +
  labs(title = "Ecoregion Protection Equality - Corrected",
      y = "Protection equality",
      x = "Year", 
      col = "Protected area class")
   

```


```{r}
ggsave(here("figures/Corrected_Protection_equality.png"), width = 10, height= 6)
```


#Plot by protection type 
##Strict
```{r}

pe_long_strict <- pe_long%>%
  group_by(PE_type)%>%
  filter(PE_type == "Strict_PE")

pe_corrected_long_strict <- pe_corrected_long%>%
  group_by(PE_type)%>%
  filter(PE_type == "Strict_PE")

```


```{r}
ggplot() +
  theme_bw() +
  geom_line(data = pe_long_strict, aes(x = Year, y = PE, col = "Baseline")) +
  geom_line(data = pe_corrected_long_strict, aes(x = Year, y = PE, col = "Corrected")) +
  scale_colour_discrete(type = colPalette, labels = c("Baseline", "Corrected")) + 
  labs(title = "Ecoregion Protection Equality - Strict",
      y = "Protection equality",
      x = "Year",
      col = "Type")

```

```{r}
ggsave(here("figures/Strict_PE.png"), width = 10, height= 6)
```

##Non strict
```{r}

pe_long_non_strict <- pe_long%>%
  group_by(PE_type)%>%
  filter(PE_type == "Non_strict_PE")

pe_corrected_long_non_strict <- pe_corrected_long%>%
  group_by(PE_type)%>%
  filter(PE_type == "Non_strict_PE")

```


```{r}
ggplot() +
  theme_bw() +
  geom_line(data = pe_long_non_strict, aes(x = Year, y = PE, col = "Baseline")) +
  geom_line(data = pe_corrected_long_non_strict, aes(x = Year, y = PE, col = "Corrected")) +
  scale_colour_discrete(type = colPalette, labels = c("Baseline", "Corrected")) + 
  labs(title = "Ecoregion Protection Equality - Non-strict",
      y = "Protection equality",
      x = "Year",
      col = "Type")

```

```{r}
ggsave(here("figures/Non_strict_PE.png"), width = 10, height= 6)
```


#Plot MPG 
##Load in data 

```{r}
mpg<- read_csv(here("output_data/results/MPG_baseline_calculations.csv"))
```

##Create new data frame for MPG 
```{r}

mpg_long <- pivot_longer(mpg, cols= c("Capad_MPG", "Strict_MPG", "Non_Strict_MPG"),
                         names_to = "MPG_type",
                         values_to = "MPG")
mpg_long<- mpg_long%>% 
  dplyr::select(-c(Capad_N,Strict_N,Non_Strict_N))

```

##Plot
```{r}

ggplot(mpg_long, aes(x = Year, y = MPG, col = MPG_type)) +
  geom_line() +
  theme_bw() +
  scale_colour_discrete(type = colPalette, labels = c("All MPAs", "Non-strict", "Strict")) +
  labs(title = "Mean Protection Gap - Baseline",
      y = "Mean Protection Gap",
      x = "Year",
      col = "Protected area class")
   
```

```{r}
ggsave(here("figures/All_PAs_MPG.png"), width =10, height=6)
```



#Plot corrected MPG
```{r}
mpg_corrected<- read_csv(here("output_data/results/MPG_corrected_calculations.csv"))
```

##Create new data frame for MPG 
```{r}

mpg_corrected_long <- pivot_longer(mpg_corrected, cols= c("Capad_MPG", "Strict_MPG", "Non_Strict_MPG"),
                         names_to = "MPG_type",
                         values_to = "MPG")
mpg_corrected_long<- mpg_corrected_long%>% 
  dplyr::select(-c(Capad_N,Strict_N,Non_Strict_N))

```

##Plot
```{r}

ggplot(mpg_corrected_long, aes(x = Year, y = MPG, col = MPG_type)) +
  geom_line() +
  theme_bw() +
  scale_colour_discrete(type = colPalette, labels = c("All MPAs", "Non-strict", "Strict")) +
  labs(title = "Mean Protection Gap - Corrected",
      y = "Mean Protection Gap",
      x = "Year",
      col = "Protected area class")
   
```

```{r}
ggsave(here("figures/Corrected_MPG.png"), width =10, height=6)
```


#Plot by protection type 
##Strict
```{r}
mpg_long_strict <- mpg_long%>%
  group_by(MPG_type)%>%
  filter(MPG_type == "Strict_MPG")

mpg_corrected_long_strict <- mpg_corrected_long%>%
  group_by(MPG_type)%>%
  filter(MPG_type == "Strict_MPG")

```


```{r}
ggplot() +
  theme_bw() +
  geom_line(data = mpg_long_strict, aes(x = Year, y = MPG, col = "Baseline")) +
  geom_line(data = mpg_corrected_long_strict, aes(x = Year, y = MPG, col = "Corrected")) +
  scale_colour_discrete(type = colPalette, labels = c("Baseline", "Corrected")) + 
  labs(title = "Ecoregion Protection Gap - Strict",
      y = "Mean protection gap",
      x = "Year",
      col = "Type")

```


```{r}
ggsave(here("figures/Strict_MPG.png"), width =10, height=6)
```


##Non strict
```{r}
mpg_long_non_strict <- mpg_long%>%
  group_by(MPG_type)%>%
  filter(MPG_type == "Non_Strict_MPG")

mpg_corrected_long_non_strict <- mpg_corrected_long%>%
  group_by(MPG_type)%>%
  filter(MPG_type == "Non_Strict_MPG")

```


```{r}
ggplot() +
  theme_bw() +
  geom_line(data = mpg_long_non_strict, aes(x = Year, y = MPG, col = "Baseline")) +
  geom_line(data = mpg_corrected_long_non_strict, aes(x = Year, y = MPG, col = "Corrected")) +
  scale_colour_discrete(type = colPalette, labels = c("Baseline", "Corrected")) + 
  labs(title = "Ecoregion Protection Gap - Non-strict",
      y = "Mean protection gap",
      x = "Year",
      col = "Type")

```


```{r}
ggsave(here("figures/Non_strict_MPG.png"), width =10, height=6)
```
