---
title: "Untitled"
author: "Jade"
date: "2024-07-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Required packages 
```{r}
library(sf)
library(here)
library(tidyverse)
library(lubridate)

```

#Baseline areas
```{r}
capad <- st_read(here("output_data/Capad_baseline/All_MPA_baseline.shp"))
strict<-  st_read(here("output_data/Capad_baseline/Strict_baseline.shp"))
non_strict <- st_read(here("output_data/Capad_baseline/Non_strict_baseline.shp"))
view(strict)
```

```{r}

capad_area <-
  capad %>% 
  as.data.frame(.)%>% 
  select(-geometry)%>%
  mutate(total_area_km2 = cumsum(area_km2))

view(capad_area)

```


```{r}
strict_area <-
  strict %>% 
  as.data.frame(.)%>% 
  select(-geometry)%>%
  mutate(total_area_km2 = cumsum(area_km2))

view(strict_area)
```


```{r}
non_strict_area <-
  non_strict %>% 
  as.data.frame(.)%>% 
  select(-geometry)%>%
  mutate(total_area_km2 = cumsum(area_km2))

view(non_strict_area)
```

```{r}
write.csv(capad_area, here("output_data/Total_area/Baseline_capad_area.csv"))

write.csv(strict_area, here("output_data/Total_area/Baseline_strict_area.csv"))

write.csv(non_strict_area, here("output_data/Total_area/Baseline_non_strict_area.csv"))

```


#Adjusted areas

```{r}

capad_files <- list.files(here("output_data/Capad_adjusted"), pattern = "capad_adjust_", full.names = TRUE)

  
capad_files2<- capad_files[grep("shp", capad_files)]

years<- c(2003:2022)

adjust_capad_area<-data.frame(Year = NA, Capad_area = NA)

for(i in 1:length(years)){
  print(years[[i]])
  y = years[[i]]
  
  sub_capad<- st_read(capad_files2[grep(years[[i]],capad_files2)])

  capad_area <-
  sub_capad %>% 
  as.data.frame(.)%>% 
  select(-geometry)%>%
  mutate(total_area_km2 = cumsum(new_capad_))%>%
  filter(Year == max(sub_capad$Year))
  
  adjust_capad_area[i,"Year"]<-y
  adjust_capad_area[i, "Capad_area"]<-capad_area$total_area_km2
  
}

```



```{r}

strict_files <- list.files(here("output_data/Capad_adjusted"), pattern = "strict_adjust", full.names = TRUE)

strict_only <- strict_files[!grepl("non",strict_files)]
  
strict_files2<- strict_only[grep("shp", strict_only)]

years<- c(2003:2022)

adjust_strict_area<-data.frame(Year = NA, Strict_area = NA)

for(i in 1:length(years)){
  print(years[[i]])
  y = years[[i]]
  
  sub_strict<- st_read(strict_files2[grep(years[[i]],strict_files2)])

  strict_area <-
  sub_strict %>% 
  as.data.frame(.)%>% 
  select(-geometry)%>%
  mutate(total_area_km2 = cumsum(new_strict))%>%
  filter(Year == max(sub_strict$Year))
  
  adjust_strict_area[i,"Year"]<-y
  adjust_strict_area[i, "Strict_area"]<-strict_area$total_area_km2
  
}

```


```{r}
non_strict_files <- list.files(here("output_data/Capad_adjusted"), pattern = "non_strict_adjust", full.names = TRUE)

non_strict_files2 <- non_strict_files[grep("shp",non_strict_files)]
  

years<- c(2003:2022)

adjust_non_strict_area<-data.frame(Year = NA, Npn_strict_area = NA)

for(i in 1:length(years)){
  print(years[[i]])
  y = years[[i]]
  
  sub_non_strict<- st_read(non_strict_files2[grep(years[[i]],non_strict_files2)])

  non_strict_area <-
  sub_non_strict %>% 
  as.data.frame(.)%>% 
  select(-geometry)%>%
  mutate(total_area_km2 = cumsum(new_non_st))%>%
  filter(Year == max(sub_non_strict$Year))
  
  adjust_non_strict_area[i,"Year"]<-y
  adjust_non_strict_area[i, "Non_strict_area"]<-non_strict_area$total_area_km2
  
}
```


```{r}
write.csv(adjust_capad_area, here("output_data/Total_area/Adjusted_capad_area.csv"))

write.csv(adjust_strict_area, here("output_data/Total_area/Adjusted_strict_area.csv"))

write.csv(adjust_non_strict_area, here("output_data/Total_area/Adjusted_non_strict_area.csv"))

```



